[package]
name = "day_3"
version = "0.1.0"
authors = ["Timothy Lee <u6018802@anu.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
